<?php
/**
 * CSS generation prompt — generates assets/css/theme.css.
 */

declare(strict_types=1);

require_once __DIR__ . '/system.php';

function prompt_css_system(): string
{
    return prompt_system();
}

/**
 * Build the user prompt for theme.css generation.
 *
 * @param array{
 *   theme_name: string,
 *   prefix: string,
 *   colors: array<string, string>,
 *   fonts: array{primary: string, secondary: string, primary_family: string, secondary_family: string},
 *   css_vars: array<string, string>,
 *   archetype: string,
 *   has_woocommerce: bool,
 *   sections: list<string>,
 *   pages: list<array{name: string, slug: string, file: string}>,
 *   globals_css: string|null,
 * } $data
 * @param list<string> $tailwind_classes  Unique Tailwind utility classes found in source
 */
function prompt_css_user(array $data, array $tailwind_classes): string
{
    $theme_name      = $data['theme_name']     ?? 'My Theme';
    $prefix          = $data['prefix']         ?? 'theme';
    $archetype       = $data['archetype']      ?? 'landing';
    $has_woocommerce = $data['has_woocommerce'] ?? false;
    $sections        = $data['sections']       ?? ['hero', 'footer'];

    // Colors
    $colors_list = '';
    foreach ($data['colors'] as $key => $val) {
        $colors_list .= "  --color-{$key}: {$val}\n";
    }

    // Source CSS vars
    $css_vars_list = '';
    foreach ($data['css_vars'] as $var => $val) {
        $css_vars_list .= "  {$var}: {$val}\n";
    }

    // Sections list
    $sections_list = implode(', ', $sections);

    // Tailwind classes — limit display to 150 for prompt brevity
    $tw_classes_display = '';
    if (!empty($tailwind_classes)) {
        $sample = array_slice($tailwind_classes, 0, 150);
        $tw_classes_display = implode(' ', $sample);
        if (count($tailwind_classes) > 150) {
            $tw_classes_display .= ' [... ' . (count($tailwind_classes) - 150) . ' more]';
        }
    }

    // Globals CSS (truncated)
    $globals_block = '';
    if (!empty($data['globals_css'])) {
        $truncated = strlen($data['globals_css']) > 6000
            ? substr($data['globals_css'], 0, 6000) . "\n/* ... truncated */"
            : $data['globals_css'];
        $globals_block = "=== globals.css (Base44 source) ===\n```css\n{$truncated}\n```\n\n";
    }

    $woo_note = $has_woocommerce
        ? "\n### WooCommerce note\nInclude a `/* === WOOCOMMERCE === */` section at the end with basic WooCommerce overrides: shop grid, product card, add-to-cart button, cart table, checkout form. Match the theme's color and typography system.\n"
        : '';

    return <<<PROMPT
## Theme: {$theme_name}
## CSS prefix: {$prefix}
## Archetype: {$archetype}
## Sections: {$sections_list}

### Color tokens
{$colors_list}
### Source CSS custom properties (from globals.css)
{$css_vars_list}
### Fonts
Primary: {$data['fonts']['primary']}
Secondary: {$data['fonts']['secondary']}

### Tailwind utility classes found in source
{$tw_classes_display}

### Source
{$globals_block}{$woo_note}

---

## Your task

Generate the complete `assets/css/theme.css` for the **{$theme_name}** theme.

### Architecture (Rule 9 — required order)
The file must be structured in this exact order with comment dividers:

```
/* =========================================================
   {$theme_name} Theme — assets/css/theme.css
   Generated by Base44 to WordPress (base44towordpress.com)
   ========================================================= */

/* 1. CSS Custom Properties (variables)        */
/* 2. HTML Preflight / Reset (Rule 10)         */
/* 3. Typography                               */
/* 4. Layout Utilities                         */
/* 5. Header & Navigation                      */
/* 6. [Section components - one per section]   */
/* 7. Footer                                   */
/* 8. Buttons & Form elements                  */
/* 9. Utility classes (.theme-animate etc.)    */
/* 10. Responsive breakpoints                  */
[optional: WOOCOMMERCE section]
```

### Section 1: CSS Custom Properties
Define ALL of these on `:root`:
```css
:root {
    /* Colors — override via Customizer inline CSS */
    --color-primary:    [extracted primary color];
    --color-accent:     [extracted accent];
    --color-background: [extracted bg];
    --color-text:       [extracted text];
    --color-muted:      [extracted muted or auto-derived];
    --color-border:     [extracted border or rgba of text at 15%];

    /* Typography — override via Customizer inline CSS */
    --font-heading: {$data['fonts']['primary']};
    --font-body:    {$data['fonts']['primary']};
    --font-mono:    ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
    --font-weight-heading: 700;
    --font-weight-body:    400;

    /* Font sizes */
    --font-size-hero:            3.75rem;
    --font-size-section-heading: 2.25rem;
    --font-size-body:            1rem;

    /* Spacing */
    --section-padding-y: 5rem;
    --container-max:     80rem;
    --container-px:      1.5rem;

    /* Transitions */
    --transition-base:   150ms ease;
    --transition-slow:   300ms ease;

    /* Border radius */
    --radius-sm:  0.25rem;
    --radius-md:  0.5rem;
    --radius-lg:  0.75rem;
    --radius-xl:  1rem;
    --radius-full: 9999px;
}
```

### Section 2: HTML Preflight (Rule 10 — MUST be included verbatim)
```css
html {
    -webkit-text-size-adjust: 100%;
    scroll-behavior: smooth;
    box-sizing: border-box;
}
*, *::before, *::after { box-sizing: inherit; }
body {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    margin: 0;
    padding: 0;
    background-color: var(--color-background);
    color: var(--color-text);
    font-family: var(--font-body);
    font-weight: var(--font-weight-body);
    font-size: var(--font-size-body);
    line-height: 1.5;
}
img, picture, video, canvas, svg { display: block; max-width: 100%; }
input, button, textarea, select { font: inherit; }
p, h1, h2, h3, h4, h5, h6 { overflow-wrap: break-word; }
```

### Section 3: Typography (Rule 4 — NO blanket h1-h6 weight)
```css
/* Only set font-family globally on headings */
h1, h2, h3, h4, h5, h6 {
    font-family: var(--font-heading);
    /* DO NOT set font-weight or line-height here — set per component */
}
```
Then set specific heading sizes and weights ONLY within component classes (`.{$prefix}-hero__title`, `.{$prefix}-section__title`, etc.)

### Section 4: Layout utilities
Define `.{$prefix}-container` (max-width: var(--container-max), padding: 0 var(--container-px), margin: 0 auto) and common layout helpers.

### Sections 5–7: Component CSS
For each of the detected sections ({$sections_list}), generate complete component CSS.

- Every CSS class MUST use the `{$prefix}` prefix with BEM: `.{$prefix}-[block]__[element]--[modifier]`
- Map Tailwind classes from source to exact CSS values using the mapping table in the system prompt
- For responsive text sizes, remember Rule 3: map line-height separately per breakpoint
- Faithfully recreate the visual design from the source: gradients, shadows, spacing, colors

### Section 8: Buttons & Forms
Define base button styles and form input styles that match the theme's design language.

### Section 9: Utility classes
```css
/* Scroll animations (Rule 8) */
.theme-animate {
    opacity: 0;
    transform: translateY(30px);
    transition: opacity .6s ease, transform .6s ease;
}
.theme-animate--visible {
    opacity: 1;
    transform: translateY(0);
}

/* Screen reader only */
.sr-only {
    position: absolute; width: 1px; height: 1px;
    padding: 0; margin: -1px; overflow: hidden;
    clip: rect(0,0,0,0); white-space: nowrap; border: 0;
}
```

### Section 10: Responsive breakpoints (mobile-first)
```css
/* sm: 640px */
@media (min-width: 640px) { ... }
/* md: 768px */
@media (min-width: 768px) { ... }
/* lg: 1024px */
@media (min-width: 1024px) { ... }
/* xl: 1280px */
@media (min-width: 1280px) { ... }
```

For each breakpoint, write ALL relevant overrides (font-sizes, grid columns, spacing, visibility). Remember Rule 3 for responsive font-size + line-height.

### Output format

Output exactly one file:

=== assets/css/theme.css ===
[complete CSS — no placeholders, no TODOs, production-ready]
PROMPT;
}
