<?php
/**
 * {THEME_NAME} — WordPress Theme Functions
 *
 * Auto-generated by Base44 to WordPress (base44towordpress.com)
 * Do not edit this file directly — use Appearance → Customize.
 *
 * @package {TEXT_DOMAIN}
 */

defined( 'ABSPATH' ) || exit;

define( '{CONST_PREFIX}_VERSION', '1.0.0' );
define( '{CONST_PREFIX}_URI', get_template_directory_uri() );
define( '{CONST_PREFIX}_DIR', get_template_directory() );
